### ISSUE TITLE
Cors Issue

### ISSUE THREAD

**Issue by aliabbasmalik8** [algolia/youtube-captions-scraper#10]
> Access to XMLHttpRequest at 'https://www.youtube.com/get_video_info?video_id=c6t3bW7kx6E' from origin '{domain}' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Haroenv** [comment]
This script is meant to run in node, not in the browser, YouTube indeed doesn't allow any origins
