### ISSUE TITLE
Could not find a declaration

### ISSUE THREAD

**Issue by ulziibadrakh-p** [algolia/youtube-captions-scraper#16]
Could not find a declaration file for module 'youtube-captions-scraper'

**Comment by Haroenv** [comment]
Yes, this library is not written in TypeScript, although it only has one export:

```ts
export async function getSubtitles(options: {
  videoID: string,
  lang?: 'en' | 'de' | 'fr',
}): Array<{start: string, dur: string, text: string}> {}
```

You can add the declaration to your own project, see the typescript documentation for that here: https://www.typescriptlang.org/docs/handbook/2/type-declarations.html#your-own-definitions
