### ISSUE TITLE
Legality of scraping YouTube captions

### ISSUE THREAD

**Issue by mgoldenbe** [algolia/youtube-captions-scraper#19]
I am considering using your package to provide a valuable service to the users of my Chrome extension, but am not eager to get sued by YouTube or have my Chrome extension banned by Google for breaking their terms of service by scraping captions without an express permission. The [linked article](https://blog.apify.com/is-web-scraping-legal/) gives hope that this kind of scraping might be legal, but I'd like to know this for certain. Have you clarified this issue?

**Comment by Haroenv** [comment]
As far as I understand it, the captions fall under the same license as the video (source: https://opensource.stackexchange.com/questions/10676/licence-for-youtube-captions) and thus can only be used when you have rights to it (your own videos, Creative Commons videos etc) or if it's simply a different display for the subtitles on the same page

**Comment by mgoldenbe** [comment]
Right. But since the video's creator intends the caption for personal use of the video's viewers, it stands to reason that a software product helping the viewers enhance that personal use is justified in scraping the captions on the viewer's behalf. Did you have something like this in mind when you created this package?

**Comment by Haroenv** [comment]
When creating this package, it was used to search through captions of selected videos that we either owned or had permission to, so a slightly more specific case.

I'd assume that what you're doing doesn't violate YouTube's terms of service

Note: I'm not a lawyer, this isn't legal advice
