### ISSUE TITLE
How to deal with Access-Control-Allow-Origin issue?

### ISSUE THREAD

**Issue by r6047736** [algolia/youtube-captions-scraper#2]
Failed to load https://youtube.com/get_video_info?video_id=xxxxxxx: Redirect from 'https://youtube.com/get_video_info?video_id=xxxxxxx' to 'https://www.youtube.com/get_video_info?video_id=xxxxxxx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

**Comment by iam4x** [comment]
Hi @r6047736 this is not meant to be used in a browser, Youtube will never add CORS headers to allow you the usage.

**Comment by Haroenv** [comment]
Note that there are some services that act as a reverse proxy to prevent this kind of issue. [Here's a small list (not endorsing any of them)](https://gist.github.com/jesperorb/6ca596217c8dfba237744966c2b5ab1e#bypass-client-side-for-production)

**Comment by iam4x** [comment]
With @Haroenv solution, that would imply to fork and update manually the URL of youtube.

Cheers.
