### ISSUE TITLE
Non-iterable error

### ISSUE THREAD

**Issue by cryptojojo33** [algolia/youtube-captions-scraper#22]
I am experiencing an error when I run getSubtitles with my firebase function. It used to work, but now I am getting a "invalid attempt to destructor non-iterable instance." Just curious if anyone else received this error or what I can do to fix.

**Comment by Haroenv** [comment]
is this still present with the latest version? If not yet updated, could you check? issue seems the same as #20

**Comment by cryptojojo33** [comment]
Re ran update and issue was fixed, my apologies. Update got released recently. Appreciate the update. Thank you
