### ISSUE TITLE
Snyk alerts axios is old

### ISSUE THREAD

**Issue by hiroshinishio** [algolia/youtube-captions-scraper#26]
Snyk alerted as follows:

Server-Side Request Forgery (SSRF) affecting package axios. No direct upgrade path, fixed in: axios@0.21.1 (Snyk)Snyk Open Source[SNYK-JS-AXIOS-1038255](https://snyk.io/vuln/SNYK-JS-AXIOS-1038255)
Regular Expression Denial of Service (ReDoS) affecting package axios. No direct upgrade path, fixed in: axios@0.21.3 (Snyk)Snyk Open Source[SNYK-JS-AXIOS-1579269](https://snyk.io/vuln/SNYK-JS-AXIOS-1579269)
Denial of Service (DoS) affecting package axios. No direct upgrade path, fixed in: axios@0.18.1 (Snyk)Snyk Open Source[SNYK-JS-AXIOS-174505](https://snyk.io/vuln/SNYK-JS-AXIOS-174505)
Cross-site Request Forgery (CSRF) affecting package axios. No direct upgrade path, fixed in: axios@1.6.0 (Snyk)Snyk Open Source[SNYK-JS-AXIOS-6032459](https://snyk.io/vuln/SNYK-JS-AXIOS-6032459)

I don't know if I can ignore this alert.

**Comment by dfdeagle47** [comment]
@Haroenv I've created https://github.com/algolia/youtube-captions-scraper/pull/29 to address this issue.

**Comment by Haroenv** [comment]
published :)
