### ISSUE TITLE
Fails for `en` and videoId `JueUvj6X3DA`

### ISSUE THREAD

**Issue by syzer** [algolia/youtube-captions-scraper#3]
Do you accept PR's ?
Because I have a fix and not sure shall I publish fix on npm or PR here..
Ok I did both.
BTW Great work guys.

**Comment by magician11** [comment]
I just tried this..

```
const { getSubtitles } = require('youtube-captions-scraper');

getSubtitles({
  videoID: 'JueUvj6X3DA',
  lang: 'en'
}).then(captions => {
  console.log(captions);
});
```

and it works fine. I see there is a PR. Has it not been merged because this works?

**Comment by syzer** [comment]
Maybe now it works... 👍 
It wasn't the case earlier.

**Comment by rvizcaino80** [comment]
Hi, thanks for the great work. Some videos are still not working for english subtitles!

Try this one Uar2hXRrckY. Thanks.

**Comment by syzer** [comment]
@rvizcaino80 
Here's fix for this one : 
```npm i --save youtube-captions-scraper-fix```
